### ISSUE TITLE
Generated QR codes are not readable using Zapper (QR Droid)

### ISSUE THREAD

**Issue by fuxoft** [speedata/luaqrcode#2]
None of the QR codes generated by luaqrcode are readable in the QR Droid (Android app) using the default "Zapper" recognition method. They are not recognized as QR codes at all. When I switch the recognition method to "ZXing", the same codes are perfectly readable. One example of such a code [is here](https://imgur.com/a/cfQiL) (the four letters "ahoj" are encoded).

**Comment by fuxoft** [comment]
Solved! I was switching the row and column index so the whole code was printed mirrored (which is apparently recognized by ZXing but not by Zapper). Sorry.

**Comment by pgundlach** [comment]
Thanks for trying out luaqrcode. If you have any question, just ask!

**Comment by fuxoft** [comment]
@pgundlach I am succesfully using it in my project https://github.com/fuxoft/krypta which generates Bitcoin keys and addresses from secret passphrases. I am not quite familiar with how your licence works so if you think I didn't give you full credit, please let me know. My app is intentionally one single large Lua file (for security reasons) so I had to slightly change some things in your app in order to make it interoperate smoothly with my scripts. Also, my Krypta is written for LuaJIT only so I can use native bxor.

**Comment by pgundlach** [comment]
krypta looks interesting! 

I think the 3 clause BSD requires to mention the use/origin/... of the library somewhere which you have done in the source code. So as far as I understand, everything is fine. (It is definately fine for me.)

Thanks for the pointer with luajit and native bxor. Since I use luajit as well, I can try to optimize the code.
