### ISSUE TITLE
Cannot reproduce the QR from the homepage?

### ISSUE THREAD

**Issue by Omikhleia** [speedata/luaqrcode#7]
Greetings,
This is an interesting library!
I tried to reproduce the QR from the homepage site:
![QR from website](http://speedata.github.io/luaqrcode/images/qrcode.gif)

According to [Zxing](https://zxing.org/w/decode.jspx), it contains the URL `http://speedata.github.com/luaqrcode/` so I tried to reproduce it (changing the EC levels, just in case), to no avail:

![image](https://user-images.githubusercontent.com/18075640/206557018-32d4f9a5-1de9-410a-8a84-19561b10b662.png)

Is there any reason for that?

(Zxing could decode all of them. I also tried other QR generators that gave different images - So I assume there's some variability perhaps - but I would have at least expected the library to generate the same output as its own homepage?)

Small standalone program reproducing my above output, in case I misinterpreted something.
```lua
local q = require("lua-libraries/qrencode")
pl = require("pl.import_into")()

for ec = 1, 4 do
  local ok, tab_or_message = q.qrcode("http://speedata.github.com/luaqrcode/", ec)
  for _, col in ipairs(tab_or_message) do
    print(table.concat(pl.tablex.map(function(cell) return cell < 0 and " " or "█" end, col), ""))
  end   
  print("\n\n")
end
```
(I may have inverted columns and lines, but that's just an axial symmetry).

**Comment by pgundlach** [comment]
I assume that the encoding algorithm changed meanwhile. The image is very old (2012) and there have been some fixes to the library (45315ec5db1abb3d33c5c9f9aad01f7c997af09d or db3443c08bb8b52f233f7db104edc8f714584ec8)
